'use client';
import {useEffect,useState} from 'react';
import {Toaster,toast} from 'sonner';
import {AppContext,emptyState,Heading,Section,CardLink,Logo,Icon,SelectField,Meter} from './shared';
import {AppState,Profile,instruments,curriculum} from '@/lib/content';
const defaults:Profile={name:'',instrument:'guitar',level:'Principiante',goal:'Tocar mis primeras canciones',minutes:20,settings:{}};
export default function Armoniq({route,item,user}:{route:string;item?:string;user:{name:string;email:string}|null}){
 const [data,setData]=useState<AppState>(emptyState),[loading,setLoading]=useState(!!user),[error,setError]=useState('');
 async function reload(){const r=await fetch('/api/state',{cache:'no-store'});const body=await r.json() as AppState & {error?:string};if(!r.ok)throw new Error(body.error);setData(body);}
 async function save(payload:Record<string,unknown>){const r=await fetch('/api/state',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});const body=await r.json() as Record<string,unknown>;if(!r.ok)throw new Error(String(body.error));return body;}
 useEffect(()=>{if(user)reload().catch(e=>setError(e.message)).finally(()=>setLoading(false));},[]);
 const profile=data.profile||{...defaults,name:user?.name||''};
 const publicPage=['bienvenida','acceso','privacidad','swift'].includes(route);
 return <AppContext.Provider value={{data,profile,user,reload,save}}><Toaster position="top-center" richColors/>
 {(route==='bienvenida'||(!user&&!publicPage))?<Welcome/>:route==='acceso'?<Welcome login/>:loading?<div className="loading"><Logo/><p>Cargando tu espacio musical…</p></div>:error?<div className="loading"><Logo/><h1>Tu música sigue aquí</h1><p role="alert">{error}</p><button className="button" onClick={()=>{setLoading(true);reload().then(()=>setError('')).catch(e=>setError(e.message)).finally(()=>setLoading(false));}}>Reintentar</button></div>:<div className="app"><header className="topbar"><Logo/><nav aria-label="Navegación principal" className="desktop-nav">{[['inicio','home','Inicio'],['aprender','learn','Aprender'],['practica','guitar','Práctica'],['canciones','library','Biblioteca'],['swift','spark','Swift (iOS)']].map(([path,icon,name])=><a key={path} className={route===path?'active':''} href={'/'+path}><Icon name={icon} size={18}/>{name}</a>)}</nav><a className="avatar" href="/perfil" aria-label="Mi perfil">{profile.name?.charAt(0).toUpperCase()||<Icon name="user"/>}</a></header>
 <main id="main" className="main">{route==='privacidad'?<Privacy/>:(!data.profile||route==='perfil-musical')?<Onboarding initial={profile}/>:route==='inicio'?<Dashboard/>:<FeatureRouter route={route} item={item}/>}</main>
 <footer className="footer"><Logo/><span>Un poco de música hace todo mejor.</span><a href="/swift">Código Swift</a><a href="/privacidad">Privacidad</a></footer>
 <nav className="bottom-nav" aria-label="Navegación móvil">{[['inicio','home','Inicio'],['aprender','learn','Aprender'],['practica','guitar','Práctica'],['canciones','library','Biblioteca'],['perfil','user','Perfil']].map(([path,icon,name])=><a key={path} className={route===path?'active':''} href={'/'+path}><Icon name={icon}/><span>{name}</span></a>)}</nav></div>}
 </AppContext.Provider>;
}
import {useApp} from './shared';
import FeatureRouter from './features';
function Welcome({login=false}:{login?:boolean}){return <div className="welcome"><div className="welcome-photo" role="img" aria-label="Guitarra acústica junto a un piano en una sala iluminada"/><div className="welcome-body"><Logo/><div className="welcome-copy"><p className="eyebrow">TU HISTORIA SUENA BIEN</p><h1>{login?'Vuelve a tu música.':'Aprende música a tu ritmo.'}<span className="title-spark">✳</span></h1><p>De tu primera nota a esa canción que siempre quisiste tocar. Encuentra tu camino, un día a la vez.</p></div><div className="welcome-benefits">{[['book','Lecciones paso a paso'],['wave','Escucha en tiempo real'],['music','Tu propia práctica']].map(([icon,text])=><div key={icon}><span className="icon-bubble"><Icon name={icon}/></span><strong>{text}</strong></div>)}</div><a className="button large" target="_top" href="/signin-with-chatgpt?return_to=%2Finicio">{login?'Continuar con ChatGPT':'Comenzar con ChatGPT'}</a><p className="auth-note"><Icon name="shield" size={16}/> Tu progreso, guardado en tu cuenta.</p><a className="text-link" href={login?'/bienvenida':'/acceso'}>{login?'Conoce Armoniq':'Ya tengo una cuenta'}</a><a className="small-link" href="/privacidad">Privacidad y uso del micrófono</a></div></div>;}
function Onboarding({initial}:{initial:Profile}){
 const {save,reload}=useApp();const[p,setP]=useState(initial),[busy,setBusy]=useState(false);
 return <><Heading eyebrow="TU PERFIL MUSICAL" title="Cada instrumento abre una historia." subtitle="Cuéntanos un poco de ti. Tu camino empieza aquí."/><form onSubmit={async e=>{e.preventDefault();setBusy(true);try{await save({action:'profile',profile:p});await reload();location.assign('/inicio');}catch(e){toast.error((e as Error).message);}finally{setBusy(false);}}}>
 <div className="onboarding-grid"><div><label className="field"><span>¿Cómo te llamas?</span><input value={p.name} maxLength={60} required placeholder="Tu nombre" onChange={e=>setP({...p,name:e.target.value})}/></label><Section title="Elige tu instrumento"><div className="instrument-grid">{instruments.map(i=><button type="button" aria-pressed={p.instrument===i.id} key={i.id} className={'instrument-card '+(p.instrument===i.id?'selected':'')} onClick={()=>setP({...p,instrument:i.id})}><span className="icon-bubble"><Icon name={i.icon} size={32}/></span><strong>{i.name}</strong><p>{i.description}</p>{p.instrument===i.id&&<span className="selected-check"><Icon name="check" size={14}/></span>}</button>)}</div></Section></div><aside className="panel onboarding-aside"><img src="/images/studio.png" alt="Guitarra de madera en un espacio de práctica" className="aside-photo"/><h2>A tu ritmo, de verdad.</h2><SelectField label="Tu experiencia" value={p.level} onChange={level=>setP({...p,level})} options={['Principiante','Intermedio','Avanzado'].map(value=>({value,label:value}))}/><SelectField label="Tu objetivo" value={p.goal} onChange={goal=>setP({...p,goal})} options={['Tocar mis primeras canciones','Mejorar mi técnica','Aprender teoría musical','Componer e improvisar'].map(value=>({value,label:value}))}/><SelectField label="Tiempo al día" value={String(p.minutes)} onChange={v=>setP({...p,minutes:Number(v)})} options={[5,10,15,20,30,45,60].map(v=>({value:String(v),label:v+' minutos'}))}/><p className="muted">La ruta completa de acordes comienza con guitarra. Los demás instrumentos incluyen fundamentos, ritmo y herramientas de práctica.</p><button className="button full" disabled={busy}>{busy?'Guardando…':'Guardar mi perfil musical'}</button></aside></div></form></>;
}
function Dashboard(){
 const {profile,data}=useApp();const list=curriculum(profile.instrument),done=data.completions.filter(c=>c.instrument===profile.instrument),next=list.find(l=>!done.some(c=>c.lesson_id===l.id))||list[0],pct=Math.round(done.length/list.length*100),minutes=Math.floor(data.sessions.reduce((a,s)=>a+s.seconds,0)/60);
 const inst=instruments.find(i=>i.id===profile.instrument)!;
 return <><div className="dashboard-greeting"><div><p className="eyebrow">TU MOMENTO MUSICAL</p><h1>Hola, {profile.name.split(' ')[0]} <span className="sun"><Icon name="sun" size={35}/></span></h1><p>Un poco de música hace todo mejor.</p></div><a className="instrument-pill" href="/perfil-musical"><Icon name={inst.icon}/>{inst.name}<Icon name="settings" size={16}/></a></div>
 <div className="dashboard-top"><a className="continue-card" href={'/leccion/'+next.id}><img src="/images/studio.png" alt="Guitarra acústica preparada para practicar"/><div><p className="eyebrow light">TU SIGUIENTE PEQUEÑO GRAN PASO</p><h2>{next.title}</h2><p>{next.subtitle}</p><div className="hero-progress"><Meter value={pct} label="Ruta completada"/><span>{pct}%</span></div><p className="hero-meta"><Icon name="book" size={18}/>{inst.name} · {next.minutes} min</p><span className="button"><Icon name="play" size={17}/>Continuar aprendiendo</span></div></a>
 <aside className="today-card panel"><span className="icon-bubble orange"><Icon name="flame" size={26}/></span><p className="eyebrow">TU PLAN DE HOY</p><h2>{profile.minutes} minutos<br/>para ti.</h2><p>La constancia empieza con un pequeño momento.</p><a className="today-step" href="/estudio"><span>01</span><div>Calentamiento<small>Encuentra tu sonido</small></div><Icon name="next" size={18}/></a><a className="today-step" href={'/leccion/'+next.id}><span>02</span><div>{next.category}<small>Un paso en tu camino</small></div><Icon name="next" size={18}/></a><a className="today-step" href="/ritmo"><span>03</span><div>Ritmo<small>Termina con un reto</small></div><Icon name="next" size={18}/></a></aside></div>
 <Section title="Todo para tu práctica" href="/practica" label="Explorar herramientas"><div className="tools-grid"><CardLink href="/afinador" icon="wave" title="Afinador" detail="Encuentra tu sonido."/><CardLink href="/metronomo" icon="tempo" color="orange" title="Metrónomo" detail="Haz tuyo el pulso."/><CardLink href="/acordes" icon="guitar" title="Acordes" detail="Explora nuevas formas."/><CardLink href="/canciones" icon="music" color="orange" title="Canciones" detail="Dale vida a lo aprendido."/></div></Section>
 <div className="dashboard-bottom"><Section title="Tu historia, en progreso" href="/perfil" label="Ver mi progreso"><div className="stats-row"><div><span className="stat-number">{done.length}<small> / {list.length}</small></span><p>Lecciones completadas</p></div><div><span className="stat-number">{minutes}<small> min</small></span><p>Tiempo practicado</p></div><div><span className="stat-number">{data.sessions.length}</span><p>Sesiones guardadas</p></div></div></Section><a href="/profesor" className="coach-card"><span className="icon-bubble"><Icon name="spark"/></span><div><p className="eyebrow">TU GUÍA DE PRÁCTICA</p><h3>Un paso a la vez.</h3><p>Encuentra qué practicar hoy según tu progreso.</p></div><Icon name="next"/></a></div></>;
}
function Privacy(){return <article className="reading"><Heading title="Tu música. Tus datos." subtitle="Privacidad en Armoniq"/><h2>Micrófono</h2><p>Solo se activa cuando pulsas Escuchar. El afinador analiza audio en tu navegador. No enviamos ni almacenamos ese audio en el servidor. Al detener la escucha se apagan las pistas del micrófono.</p><h2>Tu cuenta</h2><p>El acceso usa la identidad de ChatGPT. Guardamos tu nombre elegido, instrumento, objetivo, preferencias, lecciones completadas y resúmenes de sesiones. Cada cuenta solo puede consultar y modificar sus propios datos.</p><h2>Grabaciones</h2><p>En el estudio puedes grabar y descargar audio. La grabación permanece en memoria del navegador y desaparece al cerrar la página; no se sube automáticamente.</p><h2>Control de tus datos</h2><p>Puedes exportar tus datos y borrar tu perfil musical desde Mi perfil. Esto no elimina tu cuenta de ChatGPT.</p><h2>Evaluaciones</h2><p>Las puntuaciones de oído y ritmo describen los ejercicios realizados. Las sesiones libres registran tiempo sin inventar precisión. La guía de práctica utiliza reglas de progreso; no es un profesor humano ni un diagnóstico físico.</p><a className="button" href="/inicio">Volver a mi música</a></article>;}


