'use client';
import {useEffect,useState,useRef} from 'react';
import {toast} from 'sonner';
import {Tabs,TabsList,TabsTrigger,TabsContent} from '@/components/ui/tabs';
import {Heading,Section,CardLink,Icon,ChordDiagram,PlayChord,Meter,useApp,SelectField,timeLabel} from './shared';
import {curriculum,chords,songs,noteNames,noteName,frequency,instruments} from '@/lib/content';
import {playNotes,tone} from '@/lib/audio';
import {useMetronome} from './audio-tools';
export function Learn(){
 const{profile,data}=useApp(),list=curriculum(profile.instrument),completed=data.completions.filter(c=>c.instrument===profile.instrument);
 return <><Heading eyebrow="TU CAMINO MUSICAL" title="Cada nota cuenta." subtitle="Aprende, escucha y llévalo a tu instrumento. Un paso a la vez."><a href="/perfil-musical" className="instrument-pill"><Icon name="guitar"/>{instruments.find(i=>i.id===profile.instrument)?.name}</a></Heading><div className="tool-layout"><div className="lesson-list">{list.map((l,i)=><a key={l.id} href={'/leccion/'+l.id} className={'lesson-row '+(completed.some(c=>c.lesson_id===l.id)?'done':'')}><span className="lesson-number">{completed.some(c=>c.lesson_id===l.id)?<Icon name="check"/>:String(i+1).padStart(2,'0')}</span><div><p className="eyebrow">{l.category}</p><h3>{l.title}</h3><p>{l.subtitle}</p></div><span>{l.minutes} min</span><Icon name="next" size={18}/></a>)}</div><aside className="panel"><img className="aside-photo" src="/images/studio.png" alt="Tu espacio para hacer música"/><h2 style={{margin:'25px 0 15px'}}>Sin prisa.<br/>Con propósito.</h2><p>{completed.length} de {list.length} lecciones completadas.</p><div style={{margin:'20px 0'}}><Meter value={completed.length/list.length*100} label="Progreso de lecciones"/></div><p className="muted">Completar una lección registra que terminaste su contenido. El dominio musical se construye practicando.</p><a href="/ritmo" className="button secondary full">Practicar mi ritmo</a>{profile.instrument!=='guitar'&&<p className="notice">Aquí encontrarás fundamentos y práctica rítmica. El contenido específico de este instrumento se ampliará en próximas versiones.</p>}</aside></div></>;
}
export function Lesson({id}:{id?:string}){
 const{profile,save,reload}=useApp(),list=curriculum(profile.instrument),lesson=list.find(l=>l.id===id),[step,setStep]=useState(0),[tab,setTab]=useState('aprende'),[busy,setBusy]=useState(false);
 if(!lesson)return <><Heading title="Elige una lección" subtitle="Esta lección no está disponible para tu instrumento actual."/><a className="button" href="/aprender">Ver mi ruta</a></>;
 async function complete(){setBusy(true);try{await save({action:'complete',lessonId:lesson!.id,instrument:profile.instrument});await reload();toast.success('Lección completada');location.assign('/aprender');}catch(e){toast.error((e as Error).message);}finally{setBusy(false);}}
 return <><a className="chip" href="/aprender">Mi ruta de aprendizaje</a><div style={{marginTop:25}}><Heading eyebrow={instruments.find(i=>i.id===profile.instrument)?.name+' · LECCIÓN '+(list.indexOf(lesson)+1)+' DE '+list.length} title={lesson.title} subtitle={lesson.subtitle}/></div><Tabs className="lesson-tabs" value={tab} onValueChange={setTab}><TabsList><TabsTrigger value="aprende"><Icon name="book" size={17}/>Aprende</TabsTrigger><TabsTrigger value="practica"><Icon name="guitar" size={17}/>Practica</TabsTrigger><TabsTrigger value="resumen"><Icon name="check" size={17}/>Resumen</TabsTrigger></TabsList><TabsContent value="aprende"><div className="two-cols"><div className="panel tool-main">{lesson.chord?<><ChordDiagram chord={lesson.chord}/><PlayChord chord={lesson.chord}/></>:<><img src="/images/studio.png" className="aside-photo" style={{height:270}} alt="Guitarra y piano en un espacio tranquilo"/><p className="muted">Haz espacio para tu música.</p></>}</div><div className="panel"><p className="eyebrow">PASO {step+1} DE {lesson.steps.length}</p><p className="step-copy">{lesson.steps[step]}</p><div className="step-footer"><button className="button secondary" disabled={step===0} onClick={()=>setStep(step-1)}>Anterior</button><button className="button" onClick={()=>step<lesson.steps.length-1?setStep(step+1):setTab('practica')}>{step<lesson.steps.length-1?'Siguiente':'Vamos a practicar'}</button></div></div></div></TabsContent><TabsContent value="practica"><div className="panel reading"><h2>Ahora, a tu instrumento.</h2><p className="step-copy" style={{margin:'25px 0'}}>{lesson.task}</p><div className="two-cols"><CardLink href={lesson.id==='afinacion'?'/afinador':lesson.id==='pulso'?'/ritmo':lesson.id==='cancion'?'/cancion/nuevo-dia':'/estudio'} title="Abrir práctica" detail="Ponlo en acción." icon="play"/><CardLink href="/metronomo" title="Metrónomo" detail="Empieza despacio." icon="tempo" color="orange"/></div><div className="notice">Practica a una velocidad cómoda. Si el sonido no sale limpio, revisa una cuerda a la vez.</div><button className="button" onClick={()=>setTab('resumen')}>Ya practiqué, continuar</button></div></TabsContent><TabsContent value="resumen"><div className="panel reading"><span className="icon-bubble orange"><Icon name="check"/></span><h2 style={{margin:'20px 0'}}>Un paso más en tu historia.</h2><p>Hoy trabajaste: {lesson.title.toLowerCase()}. Vuelve a esta lección cuando necesites recordarla.</p><p className="muted">Esta confirmación registra tu avance en el contenido; no es una evaluación automática de tu interpretación.</p><button className="button" disabled={busy} onClick={complete}>{busy?'Guardando…':'Completar lección'}</button></div></TabsContent></Tabs></>;
}
export function PracticeHub(){return <><Heading eyebrow="HAZ ESPACIO PARA TU MÚSICA" title="Tu estudio de práctica" subtitle="Todo lo que necesitas para escuchar, explorar y mejorar."/><div className="tool-list">{[
 ['/afinador','wave','Afinador inteligente','Cada cuerda en su lugar.'],['/metronomo','tempo','Metrónomo','Encuentra un pulso constante.'],['/estudio','mic','Práctica libre','Toca, graba y escucha.'],['/acordes','guitar','Explorador de acordes','Formas, notas y sonidos.'],['/notas','piano','Explorador de notas','Descubre tu instrumento.'],['/ritmo','activity','Entrenador de ritmo','Mide tu precisión al pulsar.'],['/oido','headphones','Entrenamiento auditivo','Aprende a reconocer notas.'],['/canciones','music','Canciones y estudios','Une lo que has aprendido.'],['/profesor','spark','Guía de práctica','Tu siguiente paso musical.']
 ].map(([href,icon,title,detail],i)=><CardLink key={href} {...{href,icon,title,detail}} color={i%2?'orange':'green'}/>)}</div></>;}
export function Chords(){
 const{data,save,reload}=useApp(),[query,setQuery]=useState(''),[selected,setSelected]=useState('G'),[view,setView]=useState('guitarra');const c=chords[selected];
 return <><Heading title="Un acorde. Muchas posibilidades." subtitle="Explora su forma, descubre sus notas y escucha cómo suena."/><div className="tool-layout"><div><input className="search" aria-label="Buscar acorde" placeholder="Busca C, G, Em, Cmaj7…" value={query} onChange={e=>setQuery(e.target.value)}/><div className="chips" style={{margin:'20px 0'}}>{Object.keys(chords).filter(k=>(k+' '+chords[k].name).toLowerCase().includes(query.toLowerCase())).map(k=><button className={'chip '+(selected===k?'active':'')} key={k} onClick={()=>setSelected(k)}>{k}</button>)}</div>{Object.keys(chords).filter(k=>(k+' '+chords[k].name).toLowerCase().includes(query.toLowerCase())).length===0&&<p className="notice">Este acorde aún no está en la biblioteca. Prueba C, G, D, Em, Am, F, Cmaj7 o G7.</p>}<div className="panel tool-main"><h2>{c.name}</h2><Tabs value={view} onValueChange={setView} className="lesson-tabs"><TabsList><TabsTrigger value="guitarra">Guitarra</TabsTrigger><TabsTrigger value="piano">Piano</TabsTrigger></TabsList><TabsContent value="guitarra"><ChordDiagram chord={selected}/></TabsContent><TabsContent value="piano"><Keyboard active={c.midi.map(n=>n%12)} /></TabsContent></Tabs><PlayChord chord={selected}/></div></div><aside className="panel"><p className="eyebrow">CONOCE SU SONIDO</p><h2>{c.name}</h2><div className="divider"/><p className="muted">Notas</p><h3>{c.notes}</h3><p className="muted">Fórmula</p><h3>{c.formula}</h3><p className="notice">Dedos: 1 índice · 2 medio · 3 anular · 4 meñique. ○ cuerda al aire. × no tocar.</p><button className="button secondary full" onClick={async()=>{try{await save({action:'favorite',itemId:'chord:'+selected,enabled:!data.favorites.includes('chord:'+selected)});await reload();}catch(e){toast.error((e as Error).message);}}}><Icon name="heart"/>{data.favorites.includes('chord:'+selected)?'Quitar de favoritos':'Guardar acorde'}</button><a className="button full" style={{marginTop:15}} href="/estudio">Llevar a mi práctica</a><Section title="Prueba una progresión"><div className="chips">{['C','G','Am','F'].map(k=><button className="chip" key={k} onClick={()=>setSelected(k)}>{k}</button>)}</div></Section></aside></div></>;
}
export function Keyboard({active=[]}:{active?:number[]}){const white=[0,2,4,5,7,9,11],black=[{n:1,x:14.28},{n:3,x:28.56},{n:6,x:57.12},{n:8,x:71.4},{n:10,x:85.68}];return <div className="piano">{white.map(n=><button className={active.includes(n)?'highlight':''} key={n} onClick={()=>playNotes([60+n]).catch(()=>toast.error('No se pudo reproducir el audio.'))} aria-label={'Escuchar '+noteName(60+n)}>{noteName(60+n)}</button>)}{black.map(({n,x})=><button className={'black '+(active.includes(n)?'highlight':'')} style={{left:x+'%'}} key={n} onClick={()=>playNotes([60+n]).catch(()=>toast.error('No se pudo reproducir el audio.'))} aria-label={'Escuchar '+noteName(60+n)}>{noteNames[n]}</button>)}</div>;}
export function Notes(){
 const[selected,setSelected]=useState(0),[midiStatus,setMidiStatus]=useState(''),midi=useRef<MIDIAccess|null>(null);
 useEffect(()=>()=>{midi.current?.inputs.forEach(input=>input.onmidimessage=null);if(midi.current)midi.current.onstatechange=null;},[]);
 async function connect(){try{if(!navigator.requestMIDIAccess){setMidiStatus('MIDI no está disponible en este navegador. Puedes usar el teclado en pantalla.');return;}const access=await navigator.requestMIDIAccess({sysex:false});midi.current=access;const bind=()=>{setMidiStatus(access.inputs.size?'MIDI conectado. Toca una nota.':'No se encontró un teclado MIDI. Conéctalo por USB.');access.inputs.forEach(input=>{input.onmidimessage=e=>{const d=e.data;if(d&&(d[0]&0xf0)===0x90&&d[2]>0){setSelected(d[1]%12);setMidiStatus('Nota recibida: '+noteName(d[1]));}};});};access.onstatechange=bind;bind();}catch{setMidiStatus('No se pudo acceder a MIDI. Revisa el permiso y la conexión.');}}
 return <><Heading title="Encuentra cada nota" subtitle="Aprende dónde vive el sonido en tu instrumento."/><div className="chips">{noteNames.map((n,i)=><button className={'chip '+(selected===i?'active':'')} onClick={()=>setSelected(i)} key={n}>{n}</button>)}</div><div className="two-cols" style={{marginTop:25}}><div className="panel"><h2>Piano · {noteNames[selected]}</h2><Keyboard active={[selected]}/><button className="button secondary" onClick={connect}><Icon name="piano"/>Conectar teclado MIDI</button><p className="muted" aria-live="polite">{midiStatus}</p></div><div className="panel"><h2>Guitarra · {noteNames[selected]}</h2><p className="muted">Afinación estándar · primeros cinco trastes.</p><table className="fretboard"><thead><tr><th>Cuerda</th>{[0,1,2,3,4,5].map(n=><th key={n}>{n}</th>)}</tr></thead><tbody>{[64,59,55,50,45,40].map((n,i)=><tr key={i}><th>{noteName(n)}</th>{[0,1,2,3,4,5].map(f=><td key={f} className={(n+f)%12===selected?'lit':''}><button aria-label={'Escuchar '+noteName(n+f)} onClick={()=>playNotes([n+f]).catch(()=>toast.error('No se pudo reproducir el audio.'))}>{(n+f)%12===selected?noteNames[selected]:'·'}</button></td>)}</tr>)}</tbody></table></div></div></>;
}
export function SongLibrary(){
 const{data,save,reload}=useApp(),[query,setQuery]=useState(''),[onlyFav,setOnlyFav]=useState(false);
 const list=songs.filter(s=>(s.title+' '+s.style).toLowerCase().includes(query.toLowerCase())&&(!onlyFav||data.favorites.includes('song:'+s.id)));
 return <><Heading eyebrow="DALE VIDA A LO APRENDIDO" title="Tu próxima canción" subtitle="Estudios originales para aprender a tocar de principio a fin."/><div className="row" style={{marginBottom:25}}><input className="search" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Busca un título o estilo…" aria-label="Buscar canciones"/><button className={'chip '+(onlyFav?'active':'')} onClick={()=>setOnlyFav(!onlyFav)}><Icon name="heart" size={16}/>Favoritos</button></div><div className="song-grid">{list.map(s=><article className="song-card" key={s.id}><a href={'/cancion/'+s.id}><div className={'song-art '+s.color}><Icon name="music" size={65}/></div><div className="song-info"><p className="eyebrow">{s.style} · {s.bpm} BPM</p><h3>{s.title}</h3><p>{s.description}</p><div className="chips"><span className="chip">{s.difficulty}</span><span className="chip">{s.chords.join(' · ')}</span></div></div></a><button className="favorite" aria-label={(data.favorites.includes('song:'+s.id)?'Quitar':'Añadir')+' favorito '+s.title} onClick={async()=>{try{await save({action:'favorite',itemId:'song:'+s.id,enabled:!data.favorites.includes('song:'+s.id)});await reload();}catch(e){toast.error((e as Error).message);}}}><Icon name="heart" size={18}/>{data.favorites.includes('song:'+s.id)&&<span className="sr-only">Guardada</span>}</button></article>)}</div>{!list.length&&<p className="empty">No encontramos estudios con esos filtros.</p>}<p className="muted" style={{marginTop:30}}>Catálogo inicial: tres estudios instrumentales originales. El acompañamiento se sintetiza en el navegador; no contiene grabaciones comerciales.</p></>;
}
export function SongPlayer({id}:{id?:string}){
 const s=songs.find(s=>s.id===id)||songs[0],{profile,save,reload}=useApp(),m=useMetronome(s.bpm);
 const[section,setSection]=useState(0),[loop,setLoop]=useState(true),[backing,setBacking]=useState(true),[countIn,setCountIn]=useState(true),[session,setSession]=useState<string|null>(null),[busy,setBusy]=useState(false),[seconds,setSeconds]=useState(0);
 const accumulated=useRef(0),started=useRef(0),nodes=useRef<OscillatorNode[]>([]);
 const countBars=countIn?1:0,playingBar=m.bar-countBars,active=playingBar<0?-1:playingBar%4;
 function stop(){m.stop();nodes.current.forEach(n=>{try{n.stop();}catch{}});nodes.current=[];if(started.current){accumulated.current+=(performance.now()-started.current)/1000;started.current=0;}setSeconds(Math.floor(accumulated.current));}
 async function start(){if(busy)return;setBusy(true);try{if(!session){const r=await save({action:'start',kind:'cancion',instrument:profile.instrument});setSession(String(r.id));}await m.start((index,at)=>{const t=m.transport.current!;const bar=Math.floor(index/t.config.beats);if(index%t.config.beats===0&&bar>=countBars&&backing){const chord=s.chords[(bar-countBars)%4];chords[chord].midi.forEach((n,i)=>nodes.current.push(tone(t.ctx,frequency(n),at+i*.02,Math.min(1.8,240/m.bpm),.035)));nodes.current=nodes.current.slice(-100);}});started.current=performance.now();}catch(e){toast.error((e as Error).message);}finally{setBusy(false);}}
 useEffect(()=>{if(!m.running)return;const timer=setInterval(()=>setSeconds(Math.floor(accumulated.current+(started.current?(performance.now()-started.current)/1000:0))),500);return()=>clearInterval(timer);},[m.running]);
 useEffect(()=>{if(m.running&&playingBar>=4&&!loop){stop();setSection(v=>Math.min(s.sections.length-1,v+1));}},[playingBar,m.running,loop]);
 useEffect(()=>{if(!m.running&&started.current){accumulated.current+=(performance.now()-started.current)/1000;started.current=0;}},[m.running]);
 useEffect(()=>()=>{nodes.current.forEach(n=>{try{n.stop();}catch{}});},[]);
 async function finish(){stop();if(!session)return;setBusy(true);try{await save({action:'finish',id:session,seconds:Math.max(1,Math.floor(accumulated.current)),score:null,observations:{song:s.id,section:s.sections[section],bpm:m.bpm,source:'self_practice'}});await reload();setSession(null);accumulated.current=0;setSeconds(0);toast.success('Práctica guardada en tu perfil');}catch(e){toast.error((e as Error).message);}finally{setBusy(false);}}
 return <><a href="/canciones" className="chip">Biblioteca</a><div style={{marginTop:25}}><Heading eyebrow={s.style+' · ESTUDIO ORIGINAL'} title={s.title} subtitle={s.description}/></div><div className="tool-layout"><div className="panel tool-main"><div className="chips">{s.sections.map((name,i)=><button className={'chip '+(section===i?'active':'')} key={name} onClick={()=>{stop();setSection(i);}}>{name}</button>)}</div><div className="timeline">{s.chords.map((c,i)=><div key={i} className={m.running&&active===i?'active':''}>{c}<small>Compás {i+1}</small></div>)}</div><ChordDiagram chord={s.chords[Math.max(0,active)]}/><p aria-live="polite">{m.running&&playingBar<0?'Cuenta previa · '+(m.beat+1):m.running?s.sections[section]+' · compás '+(active+1):'Escucha, observa y toca a tu ritmo.'}</p><div className="beats">{[0,1,2,3].map(i=><span key={i} className={'beat '+(m.beat===i?'current':'')}>{i+1}</span>)}</div><div className="transport-controls"><button className="circle-button" aria-label="Reiniciar sección" onClick={stop}><Icon name="repeat"/></button><button disabled={busy} className="play-button" aria-label={m.running?'Pausar canción':'Reproducir canción'} onClick={()=>m.running?stop():start()}><Icon name={m.running?'pause':'play'} size={29}/></button><button className="circle-button" aria-label="Siguiente sección" onClick={()=>{stop();setSection((section+1)%s.sections.length);}}><Icon name="next"/></button></div><p>Tiempo de práctica · {timeLabel(seconds)}</p></div><aside className="panel tool-aside"><h2>Hazla tuya</h2><div className="divider"/><SelectField label="Velocidad" value={String(m.bpm)} onChange={v=>{stop();m.setBpm(Number(v));}} options={[.25,.5,.75,.9,1].map(v=>({value:String(Math.round(s.bpm*v)),label:Math.round(v*100)+'% · '+Math.round(s.bpm*v)+' BPM'}))}/><div className="stack"><label className="row"><span>Repetir sección</span><input type="checkbox" checked={loop} onChange={e=>{stop();setLoop(e.target.checked);}}/></label><label className="row"><span>Acompañamiento</span><input type="checkbox" checked={backing} onChange={e=>{stop();setBacking(e.target.checked);}}/></label><label className="row"><span>Cuenta previa</span><input type="checkbox" checked={countIn} onChange={e=>{stop();setCountIn(e.target.checked);}}/></label></div><p className="notice">Cada sección contiene cuatro compases. Practica los cambios y usa el bucle antes de avanzar.</p><button className="button full" disabled={!session||busy||seconds<1} onClick={finish}>Terminar y guardar</button><p className="muted">Se guarda el tiempo de práctica. Esta sesión no evalúa acordes por micrófono.</p></aside></div></>;
}



